baseURL = "https://kraashen.github.io"
title = "tracing bytes"
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = true
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["posts"]

Paginate = 10
preserveTaxonomyNames = true
# Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
pygmentsCodefences = true
# Missing translations will default to this content language
defaultContentLanguage = "en"

[params]
defaultTheme = "dark"

[minify]
disableXML = true

[params.info]
description = "programming and tech journeys, stack traces, and bits of bytes"
title404 = "Oh my! You took a wrong turn I guess. :("

[params.assets]
favicon = "favicon.ico"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

[params.copyright]
prefix = ""
holder = "Tomi Juntunen"
startYear = "2017"
suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
taxonomyCloudShuffle = true
hideMainMenu = false
rtl = false

[params.comments]
enable = false

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

[blackfriday]
hrefTargetBlank = true

[languages]
# edit this block for your own language
[languages.en.params]
lang = "en"
languageName = "English"
weight = 1
